# Generated by Django 4.0.5 on 2022-10-19 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_mail',
            name='send_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 19, 14, 11, 39, 204634)),
        ),
    ]
