# Generated by Django 4.0.5 on 2022-10-19 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0002_send_mail_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_mail',
            name='send_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 19, 14, 13, 33, 97038)),
        ),
    ]
