# Generated by Django 4.0.5 on 2022-10-19 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_gmail', '0004_read_mail_alter_send_mail_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read_mail',
            name='send_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='send_mail',
            name='send_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 19, 16, 31, 29, 201922)),
        ),
    ]
